apisix:
  node_listen: 9080
  enable_admin: true
  enable_control: true
  control:
    ip: 0.0.0.0
    port: 9092
  ssl:
    enable: false
  enable_server_tokens: false
  enable_admin_cors: true
  standalone: true
  delete_route_with_worker: true

deployment:
  role: traditional
  role_traditional:
    config_provider: yaml

admin:
  allow_admin:
    - 0.0.0.0/0
  admin_key:
    - name: admin
      key: adminkey
      role: admin
